### ISSUE TITLE
Could not minify code when building from react-scripts

### ISSUE THREAD

**Issue by jerelmiller** [callstats-io/callstats-twilio-video-js#4]
We are in the process of integrating callstats with our twilio video app. We are using react-scripts to build the app (via create-react-app), but it fails to minify.

```
$ yarn build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/callstats-twilio-video/lib/Logger.js:7

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
```

Any help would be appreciated. Thanks.

**Comment by karthikbr82** [comment]
Hi, You can use the minified file already which will be there in the dist folder. dist/callstats-twilio-video.min.js

**Comment by jerelmiller** [comment]
Hey @karthikbr82 I think the issue is that that file isn't actually installed when using `yarn add` or `npm install`. I installed this package via `yarn`, but I do not see any `dist` folder. I do see that the "main" file listed in `package.json` is the `lib/index.js`, which is the uncompiled version.

I believe this is the main reason this is blowing up. I know at least the tools inside of `react-scripts` do not minify/compile `node_modules` to speed up builds.

I've worked around this issue for now by copying the source files to my app directory itself, but this presents a problem if/when you release updates to this package since I will have to manually copy them each time.

Let me know if you need any other info from me. Thanks for the reply.

**Comment by jerelmiller** [comment]
@karthikbr82 by chance do you accept pull requests? If so, I'd be happy to take a stab at resolving this issue when I get some free time.

**Comment by karthikbr82** [comment]
@jerelmiller I think we did not pack the dist folder in the npm package, I will make a new release with dist and minified file in the dist folder, meanwhile you could run 'gulp prod' in the folder which will create the dist folder and minified file in it. 

Yes we are happy to accept pull request if you resolve it.

**Comment by burgalon** [comment]
indeed missing dist folder

**Comment by burgalon** [comment]
also getting
```[21:21:31] 'bundle' errored after 1.02 s
[21:21:31] Error: Received a non-Vinyl object in `dest()`
    at DestroyableTransform.normalize [as _transform] (/Users/burg/Downloads/callstats-twilio-video-js-master/node_modules/vinyl-fs/lib/dest/prepare.js:16:17)
    at DestroyableTransform.Transform._read (/Users/burg/Downloads/callstats-twilio-video-js-master/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/burg/Downloads/callstats-twilio-video-js-master/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/Users/burg/Downloads/callstats-twilio-video-js-master/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/Users/burg/Downloads/callstats-twilio-video-js-master/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (/Users/burg/Downloads/callstats-twilio-video-js-master/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Duplexify._write (/Users/burg/Downloads/callstats-twilio-video-js-master/node_modules/duplexify/index.js:208:22)
    at doWrite (/Users/burg/Downloads/callstats-twilio-video-js-master/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/Users/burg/Downloads/callstats-twilio-video-js-master/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/Users/burg/Downloads/callstats-twilio-video-js-master/node_modules/readable-stream/lib/_stream_writable.js:334:11)```

**Comment by imcbv** [comment]
Did anyone ever find a solution to this?

**Comment by pallab-gain** [comment]
You can try this patch to build the non-minified version of the library.

[https://gist.github.com/pallab-gain/ba67c1fd18624192a147737a4ad92719](https://gist.github.com/pallab-gain/ba67c1fd18624192a147737a4ad92719)

**Comment by karthikbr82** [comment]
@imcbv to fix this we made a release with dist and minified file in the dist folder. You could use the minified files from the dist folder now.
